travis:
  secure:
    BINSTAR_TOKEN: agNjeEWC24EHZZHQjLwx0azgHD846b2Mncbk2A4x5lTt1V5xA5U+zg1S+G8GU/48VdQEtd4XsPgkIsJCzkrq756AS1dVc9ZQx/eiAsUNFO6+qozZyfmiCKiItU6gxidufVfrpMkx6NJYf4aQGPabXlrA9sqSKG1TyOhGgMlRCxCqnQDWLdrVcUDOOvcWPbKRn+eYgQdrnM5Iew4mk/rZyYZoqpONFCZmXENB8lSzuNIKHQTB77hh4SwR4Gk+eVrLantYxBLVBvvmVpO5OvqlVMldPhoZfazxITcE+HyfOhp07wn6VT7D4TuMQyzwmNUO3BPcdstdPvvOa4biH8HHoWpPmJJxBApAAWph+/xpiDQ3UA5yjWUYqvnqBLFMG9jGPecDnZZW9U3UKr+MjLjl5j3vP/FW2/zSEdMrblHye4N/27aKvzvSeOpGt7Z8ehJSWnOB41dFm8vD9VkbO8ys8h2+7LYrI6cnqLLyDLFSqb4gcZrde1UZE3qZRVBSTcge1eGwy1P5YqSSpHT8RNcuhWUjqAefDML1T1MKWNhiBLyT/Y03ZgxcMb8gYUL37O+7Zsgn6PKA2LN2gBTSLMgaR9LMd44yFgltHr4Nvd5SCNZFm0n54bl38cLtdg5EQn5afd83CL+G6NOJABQauvtNBHpcdptp5PcBtKYXuh6mEyA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
