travis:
  secure:
    BINSTAR_TOKEN: ITpWJBGmYzh/Ubj6K0oNQkZA5od87DAlzA10xqzbkFOYcw/lzWMRyB0yUz6oywcxt5zWW3y38KRGcAtnkpBRVNygHaG29oFtdAXJrEXvyWScdaqFVxJy8oHii8+3qzgSywo8ozAorIcvz0rhQDW25c+K8QBcMmIvG2piLVP8QOFv3ru8LEiP+oKUv9eTCNNfdQBrygEiy/OftgaeypuKSN2lX9X8lxFBcn8lThtS0Eqwbu59uV7b0TXoV0TCJ3BcrOUBTq/DR0qWhZcOZ15AdVDe7xyv9LOUMnOZd2EmlVMFtpvgfoDE/zNFyeh6XJxGu87HaT6risxZkrzSPceQnR0NsGlQcwMsoQwnWNcTOWqbmdezLZwSjktBk5eNfuoenzAm8wbH8xu25oXNkJCPt7ft9n02h8XHVHIjzuOkqx0kne3hh9ywR/ZI0kQPNe59KNY7CTpinh2ufFEYvVvf28BRcWANOa0ozT4HjxeogMPgSTvPKUUqAomGHSIZvJaMlj9B8BiDPmQAjj/BLh4F4oJhyNi63SJ1dktb1waE54QsKVzunYuiylP434Nsq3IjPq4ku1wDEA0EWL9KHJZy+s/8UM0NwGk+aXH+XMZ5pjGlSvU0Dt7fwGjb+OJpjLIiPzwHixeaYDYnOWI7C5St7/9F4OGAL/06nU5xfsfZhZc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
