travis:
  secure:
    BINSTAR_TOKEN: IU/AuT6JHmGlPgY2mflT1fCsE0RM6vtj2NZk6SkyKTp780GwDKGJZ6jHl9Q/F3Yz+9qvDgWOtuqX0NijVR53JSBE5CW0iFqNrlJvb6T1mUz+2yEED1Tb996TKeTBkMstsJA70jrh9D+qQTXOhBLgLYu7lNIxqWLphGTfdeEB7RxMBM10XDONpzlBbjSZJM1EiWV0GOSI2yvWuuC0vNTthmJTEb6eF5fhNLQsWynmSjlOOywY7oYI+RaL9lP1FHpaRNEtR4P8Nfw+B44FCNR7w4PPMMaAVJuUaoYxGyRkdfQg2Lt9y40DSRtVbsjNQNjYPPJHmX+gHNtbvVtgPSksFZ7P6i6b/UffGUE9DknFyBuBfu5df0ZwmzIY4vEBQl+yZJhAryOUBP0aebUUSKPAbdvnZHPz8yjqI3A9ro9ZnfEefbf4AUtImxnCUGrTPfnp99+vOOI/0ZDV8baT7EcKvLzsQrhL+Jxr9Xekoi8y8T72FL0vHHHy5cstj+bLLvCE7QzB1XqGtQn7eh03IUWX/qznc8NypXavCQAt8FCiY/G3BkN4rRiDhKUySH9JcxeYt6+Ld4l3YpPR9JETz6OWv+69LxAJyCis1mWNMW3sSXbrqo4snDKc/adZGGXWGbYqpA+f1O7n4a6xcyoucfctUKvQqEUKZn0/3FvhpYUO8ZA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
